# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curr_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch', models.IntegerField(default=2019)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('programme', models.CharField(choices=[('B.Tech', 'B.Tech'), ('B.Des', 'B.Des'), ('M.Tech', 'M.Tech'), ('M.Des', 'M.Des'), ('PhD', 'PhD')], max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ME', 'ME'), ('Btech_ALL', 'Btech_ALL'), ('Common', 'Common'), ('Design', 'Design')], max_length=256)),
                ('batch', models.IntegerField(default=2019)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
