# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256)),
                ('course_details', models.TextField(max_length=2500)),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('ME', 'ME'), ('Btech_ALL', 'Btech_ALL'), ('Common', 'Common'), ('Design', 'Design')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Professional Core', 'Professional Core'), ('Professional Elective', 'Professional Elective'), ('Professional Lab', 'Professional Lab'), ('Engineering Science', 'Engineering Science'), ('Natural Science', 'Natural Science'), ('Humanities', 'Humanities'), ('Design', 'Design'), ('Manufacturing', 'Manufacturing'), ('Management Science', 'Management Science')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='floated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='optional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='programme',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('B.Des', 'B.Des'), ('M.Tech', 'M.Tech'), ('M.Des', 'M.Des'), ('PhD', 'PhD')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='batch',
            field=models.IntegerField(blank=True, default=2019, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='curriculum',
            unique_together=set([('batch', 'programme', 'course_code')]),
        ),
        migrations.AlterModelTable(
            name='curriculum',
            table='Curriculum_Courses',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acadmodule.Course'),
        ),
    ]
