# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0003_auto_20190907_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('course_type', models.CharField(choices=[('Core', 'Professional Core'), ('Elective', 'Professional Elective'), ('Lab', 'Professional Lab'), ('Project', 'Professional Project'), ('ES', 'Engineering Science'), ('NS', 'Natural Science'), ('HS', 'Humanities'), ('DS', 'Design'), ('MN', 'Manufacturing'), ('MS', 'Management Science')], max_length=200)),
                ('course_credits', models.IntegerField(default=0)),
                ('course_lecture', models.IntegerField(default=0)),
                ('course_tutorial', models.IntegerField(default=0)),
                ('course_practical', models.IntegerField(default=0)),
                ('course_discussion', models.IntegerField(default=0)),
                ('curr_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acadmodule.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acadmodule.BatchSemester')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=256, null=True)),
                ('head_instructor', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acadmodule.CurriculumCourse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curriculuminstructor',
            unique_together=set([('course', 'instructor')]),
        ),
        migrations.AlterUniqueTogether(
            name='curriculumcourse',
            unique_together=set([('semester', 'course_id')]),
        ),
    ]
