# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0006_auto_20190908_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchsemester',
            name='batch',
            field=models.IntegerField(default=2019, unique=True),
        ),
        migrations.AlterField(
            model_name='btechcurriculum',
            name='batch',
            field=models.IntegerField(default=2019, unique=True),
        ),
    ]
