# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-09 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0011_auto_20190909_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsemester',
            name='batch',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterField(
            model_name='btechcurriculum',
            name='batch',
            field=models.IntegerField(default=2019),
        ),
    ]
