# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0012_auto_20190909_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsemester',
            name='programme',
            field=models.CharField(choices=[('BTECH', 'BTech'), ('BDES', 'BDes'), ('MTech', 'MTech'), ('MDes', 'MDes'), ('PhD', 'PhD')], default='', max_length=30),
        ),
    ]
