# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0013_auto_20190910_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumcourse',
            name='curr_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acadmodule.Course'),
        ),
    ]
