# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0017_auto_20190910_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechcurriculum',
            name='batch',
            field=models.IntegerField(default=2019, unique=True),
        ),
    ]
