# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0018_auto_20190910_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechcurriculum',
            name='programme',
            field=models.CharField(choices=[('BTECH', 'BTech'), ('BDES', 'BDes'), ('MTech', 'MTech'), ('MDes', 'MDes'), ('PhD', 'PhD')], default='BTech', max_length=30),
        ),
    ]
