# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-11 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acadmodule', '0019_auto_20190911_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btechcurriculum',
            name='batch',
            field=models.IntegerField(default=2019),
        ),
        migrations.AlterUniqueTogether(
            name='btechcurriculum',
            unique_together=set([('programme', 'batch')]),
        ),
    ]
